services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusMessengerAdminPlugin\:
        resource: '../../*'
        exclude: '../../{Entity}'

    MonsieurBiz\SyliusMessengerAdminPlugin\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    Sylius\Component\Grid\Provider\GridProviderInterface: '@sylius.grid.provider'
    Sylius\Component\Grid\View\GridViewFactoryInterface: '@sylius.grid.view_factory'
